
package com.vertexinc.oseries.services.calculatetax70;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import vertexinc.o_series.tps._7._0.ObjectFactory;
import vertexinc.o_series.tps._7._0.VertexEnvelope;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculateTaxWS70", targetNamespace = "http://www.vertexinc.com/oseries/services/CalculateTax70")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculateTaxWS70 {


    /**
     * 
     * @param part
     * @return
     *     returns vertexinc.o_series.tps._7._0.VertexEnvelope
     */
    @WebMethod
    @WebResult(name = "VertexEnvelope", targetNamespace = "urn:vertexinc:o-series:tps:7:0", partName = "VertexEnvelope")
    public VertexEnvelope calculateTax70(
        @WebParam(name = "VertexEnvelope", targetNamespace = "urn:vertexinc:o-series:tps:7:0", partName = "part")
        VertexEnvelope part);

}
