
package com.vertexinc.oseries.services.calculatetax70;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

import com.hml.DataBaseDateFetch;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculateTaxWSService70", targetNamespace = "http://www.vertexinc.com/oseries/services/CalculateTax70", wsdlLocation = "http://vertex-dev.hermanmiller.com:80/vertex-ws/services/CalculateTax70?wsdl")
public class CalculateTaxWSService70
    extends Service
{

    private final static URL CALCULATETAXWSSERVICE70_WSDL_LOCATION;
    private final static WebServiceException CALCULATETAXWSSERVICE70_EXCEPTION;
    private final static QName CALCULATETAXWSSERVICE70_QNAME = new QName("http://www.vertexinc.com/oseries/services/CalculateTax70", "CalculateTaxWSService70");
    static String wsdlLocation=DataBaseDateFetch.getCalculateTaxUrl();
    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(wsdlLocation);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATETAXWSSERVICE70_WSDL_LOCATION = url;
        CALCULATETAXWSSERVICE70_EXCEPTION = e;
    }

    public CalculateTaxWSService70() {
        super(__getWsdlLocation(), CALCULATETAXWSSERVICE70_QNAME);
    }

    public CalculateTaxWSService70(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATETAXWSSERVICE70_QNAME, features);
    }

    public CalculateTaxWSService70(URL wsdlLocation) {
        super(wsdlLocation, CALCULATETAXWSSERVICE70_QNAME);
    }

    public CalculateTaxWSService70(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATETAXWSSERVICE70_QNAME, features);
    }

    public CalculateTaxWSService70(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculateTaxWSService70(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculateTaxWS70
     */
    @WebEndpoint(name = "CalculateTax70")
    public CalculateTaxWS70 getCalculateTax70() {
        return super.getPort(new QName("http://www.vertexinc.com/oseries/services/CalculateTax70", "CalculateTax70"), CalculateTaxWS70.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculateTaxWS70
     */
    @WebEndpoint(name = "CalculateTax70")
    public CalculateTaxWS70 getCalculateTax70(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.vertexinc.com/oseries/services/CalculateTax70", "CalculateTax70"), CalculateTaxWS70.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATETAXWSSERVICE70_EXCEPTION!= null) {
            throw CALCULATETAXWSSERVICE70_EXCEPTION;
        }
        return CALCULATETAXWSSERVICE70_WSDL_LOCATION;
    }

}
